### ISSUE TITLE
Very awesome paper, is there a next version?

### ISSUE THREAD

**Issue by Fyzjym** [omni-us/research-GANwriting#11]

**Comment by hendraet** [comment]
I'm not sure about the original authors, but just recently there was an improved version of GANwriting published (by someone else):
https://arxiv.org/pdf/2105.10528.pdf
https://github.com/MattAlexMiracle/SmartPatch

**Comment by Fyzjym** [comment]
> I'm not sure about the original authors, but just recently there was an improved version of GANwriting published (by someone else):
> https://arxiv.org/pdf/2105.10528.pdf
> https://github.com/MattAlexMiracle/SmartPatch

Sir, thanks really. It helps a lot.
