### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by ganji15** [omni-us/research-GANwriting#5]
Hi @leitro @hendraet, thanks for sharing your amazing work. 

Could you share your pre-trained model so that we can get rid of retraining one and play it right away?

I will be grateful if you could provide your pre-trained model.  Thanks in advance.

**Comment by hendraet** [comment]
You can find a model that was trained for 2000 epochs [here](https://owncloud.hpi.de/s/bmHZdxiMX5ujv21).

However, it only works for a word length of 7, so make sure that `MAX_CHARS` in `load_data.py` is set to 7. If you need longer words, you'll have to train a new one.

If you plan to evaluate the model with the `tt.test_single_writer.4_scenarios.py` script, please make sure you apply the changes proposed in #6.

**Comment by ganji15** [comment]
@hendraet Thank you very much!

**Comment by yuyukuy534** [comment]
> Hi @leitro @hendraet, thanks for sharing your amazing work.
> 
> Could you share your pre-trained model so that we can get rid of retraining one and play it right away?
> 
> I will be grateful if you could provide your pre-trained model. Thanks in advance.



> Hi @leitro @hendraet, thanks for sharing your amazing work.
> 
> Could you share your pre-trained model so that we can get rid of retraining one and play it right away?
> 
> I will be grateful if you could provide your pre-trained model. Thanks in advance.

Could you share me the pre-trained model ? I can not open it.
